"""
Billing, Usage & Feature Flag Models — Platform Service

This file contains three closely related models:

1. BillingInvoice
   The actual invoice raised for a subscription period.
   Tracks amount, payment status, due date, payment received date.

2. SubscriptionUsageSnapshot
   A monthly/daily snapshot of actual usage (student count, user count,
   storage used). Used for per-student billing calculations and quota
   enforcement.

3. TenantFeatureFlag
   Granular feature toggle per tenant. Allows enabling/disabling specific
   features independently of the subscription plan. Used for:
     - Early access features for specific tenants
     - Temporary overrides during support
     - A/B testing
     - Custom enterprise features
"""

import enum

from sqlalchemy import Column, Date, Enum, Integer, Numeric, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship

from .base import BaseModel


# ═══════════════════════════════════════════════════════════════════════════════
# BILLING INVOICE
# ═══════════════════════════════════════════════════════════════════════════════

class InvoiceStatus(str, enum.Enum):
    DRAFT = "DRAFT"           # Being prepared, not yet sent
    SENT = "SENT"             # Sent to tenant, awaiting payment
    PAID = "PAID"             # Payment received and confirmed
    OVERDUE = "OVERDUE"       # Past due date, payment not received
    PARTIALLY_PAID = "PARTIALLY_PAID"  # Partial payment received
    WAIVED = "WAIVED"         # Ops team waived the invoice (credits, etc.)
    REFUNDED = "REFUNDED"     # Payment was refunded
    VOID = "VOID"             # Invoice cancelled before payment


class BillingInvoice(BaseModel):
    """
    A formal invoice raised for a tenant's subscription.

    One invoice per billing cycle per subscription.
    Tracks amount, tax, payment status, and all payment details.
    """

    __tablename__ = "billing_invoices"

    # ── References ────────────────────────────────────────────────────────────
    tenant_id = Column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK → tenants.id",
    )
    subscription_id = Column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK → tenant_subscriptions.id. The subscription this invoice is for.",
    )

    # ── Invoice Identification ────────────────────────────────────────────────
    invoice_number = Column(
        String(50),
        nullable=False,
        unique=True,
        index=True,
        comment=(
            "Globally unique invoice number. Human-readable. "
            "E.g. 'SS-INV-2024-00001'. Generated by a sequence."
        ),
    )
    invoice_date = Column(
        Date,
        nullable=False,
        comment="Date this invoice was raised",
    )
    due_date = Column(
        Date,
        nullable=False,
        comment="Date by which payment must be received",
    )

    # ── Period Covered ────────────────────────────────────────────────────────
    billing_period_start = Column(
        Date,
        nullable=False,
        comment="Start date of the billing period this invoice covers",
    )
    billing_period_end = Column(
        Date,
        nullable=False,
        comment="End date of the billing period this invoice covers",
    )

    # ── Amounts (all in paise) ────────────────────────────────────────────────
    subtotal_paise = Column(
        Numeric(14, 0),
        nullable=False,
        default=0,
        comment="Amount before tax and discounts, in paise",
    )
    discount_paise = Column(
        Numeric(14, 0),
        nullable=False,
        default=0,
        comment="Total discount amount, in paise",
    )
    taxable_amount_paise = Column(
        Numeric(14, 0),
        nullable=False,
        default=0,
        comment="Amount after discount, before tax, in paise",
    )
    tax_rate_percent = Column(
        Numeric(5, 2),
        nullable=False,
        default=18,
        comment="GST/tax rate applied. Default 18% GST for India.",
    )
    tax_amount_paise = Column(
        Numeric(14, 0),
        nullable=False,
        default=0,
        comment="Tax amount (GST), in paise",
    )
    total_amount_paise = Column(
        Numeric(14, 0),
        nullable=False,
        default=0,
        comment="Total invoice amount including tax, in paise",
    )
    currency = Column(
        String(3),
        nullable=False,
        default="INR",
        comment="ISO 4217 currency code",
    )

    # ── Per-Student Billing (if applicable) ───────────────────────────────────
    billed_student_count = Column(
        Integer,
        nullable=True,
        comment=(
            "Number of students billed for, if pricing_model = PER_STUDENT. "
            "Taken from SubscriptionUsageSnapshot at billing time."
        ),
    )
    billed_user_count = Column(
        Integer,
        nullable=True,
        comment="Total users billed for, if pricing_model = PER_USER",
    )

    # ── GST Details (India-specific) ──────────────────────────────────────────
    gstin_of_tenant = Column(
        String(20),
        nullable=True,
        comment="Tenant's GSTIN for B2B invoice. Required for ITC claims.",
    )
    hsn_sac_code = Column(
        String(20),
        nullable=True,
        default="9984",
        comment="HSN/SAC code for the service. 9984 = online software services.",
    )
    place_of_supply = Column(
        String(50),
        nullable=True,
        comment="State of supply for GST calculation (IGST vs CGST+SGST)",
    )

    # ── Status & Payment ──────────────────────────────────────────────────────
    status = Column(
        Enum(InvoiceStatus, name="invoice_status_enum"),
        nullable=False,
        default=InvoiceStatus.DRAFT,
        index=True,
        comment="Current payment status of this invoice",
    )
    paid_amount_paise = Column(
        Numeric(14, 0),
        nullable=False,
        default=0,
        comment="Amount received so far, in paise",
    )
    paid_at = Column(
        Date,
        nullable=True,
        comment="Date full payment was received",
    )
    payment_reference = Column(
        String(255),
        nullable=True,
        comment="Payment gateway reference or bank transaction ID",
    )
    payment_method = Column(
        String(50),
        nullable=True,
        comment="How payment was received. E.g. 'NEFT', 'Razorpay', 'Cheque'",
    )

    # ── Document ──────────────────────────────────────────────────────────────
    pdf_file_id = Column(
        UUID(as_uuid=True),
        nullable=True,
        comment="File ID of the generated PDF invoice (File/Media Service)",
    )

    # ── Notes ─────────────────────────────────────────────────────────────────
    notes = Column(
        Text,
        nullable=True,
        comment="Internal notes or special terms for this invoice",
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    subscription = relationship(
        "TenantSubscription",
        back_populates="billing_invoices",
        foreign_keys=[subscription_id],
    )

    def __repr__(self) -> str:
        return (
            f"<BillingInvoice number={self.invoice_number!r} "
            f"status={self.status} total={self.total_amount_paise}>"
        )


# ═══════════════════════════════════════════════════════════════════════════════
# SUBSCRIPTION USAGE SNAPSHOT
# ═══════════════════════════════════════════════════════════════════════════════

class SubscriptionUsageSnapshot(BaseModel):
    """
    A point-in-time snapshot of a tenant's actual usage metrics.

    Captured daily (for monitoring) or at billing time (for invoicing).
    Used for:
      - Enforcing quota limits (max_students, max_users)
      - Per-student billing calculations
      - Usage trend dashboards for ops team
      - Alerting when tenant approaches quota limits

    Design note:
      This is NOT the source of truth for student/user counts.
      The actual counts live in Academic Service / Auth Service.
      This is a pre-computed snapshot to avoid cross-service queries at billing.
    """

    __tablename__ = "subscription_usage_snapshots"

    # ── References ────────────────────────────────────────────────────────────
    tenant_id = Column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK → tenants.id",
    )
    subscription_id = Column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK → tenant_subscriptions.id",
    )

    # ── Snapshot Time ─────────────────────────────────────────────────────────
    snapshot_date = Column(
        Date,
        nullable=False,
        index=True,
        comment="Date this snapshot was captured",
    )
    snapshot_type = Column(
        String(20),
        nullable=False,
        default="DAILY",
        comment=(
            "Why this snapshot was taken. "
            "DAILY = routine daily snapshot. "
            "BILLING = captured at invoice generation time. "
            "MANUAL = triggered by ops team."
        ),
    )

    # ── User Counts ───────────────────────────────────────────────────────────
    active_student_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of active (non-deleted) student accounts at snapshot time",
    )
    active_teacher_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of active teacher/staff accounts at snapshot time",
    )
    active_parent_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of active parent accounts at snapshot time",
    )
    total_user_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Total active user accounts (all roles) at snapshot time",
    )
    admin_user_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of admin/staff portal user accounts",
    )

    # ── Module Usage ──────────────────────────────────────────────────────────
    active_modules_count = Column(
        Integer,
        nullable=False,
        default=0,
        comment="Number of modules currently enabled for this tenant",
    )

    # ── Storage Usage ─────────────────────────────────────────────────────────
    storage_used_mb = Column(
        Numeric(12, 2),
        nullable=False,
        default=0,
        comment="Total storage used in MB at snapshot time",
    )

    # ── Plan Limits at Snapshot Time ──────────────────────────────────────────
    plan_max_students = Column(
        Integer,
        nullable=True,
        comment="Subscription's max_students limit at this snapshot time",
    )
    plan_max_users = Column(
        Integer,
        nullable=True,
        comment="Subscription's max_total_users limit at this snapshot time",
    )
    plan_max_storage_gb = Column(
        Integer,
        nullable=True,
        comment="Subscription's max_storage_gb at this snapshot time",
    )

    # ── Quota Breach Flags ────────────────────────────────────────────────────
    is_student_quota_exceeded = Column(
        String(5),
        nullable=False,
        default="false",
        comment="True if active_student_count > plan_max_students at snapshot time",
    )
    is_user_quota_exceeded = Column(
        String(5),
        nullable=False,
        default="false",
        comment="True if total_user_count > plan_max_users at snapshot time",
    )
    is_storage_quota_exceeded = Column(
        String(5),
        nullable=False,
        default="false",
        comment="True if storage_used_mb > plan_max_storage_gb * 1024",
    )

    # ── Additional Metrics (flexible) ─────────────────────────────────────────
    additional_metrics = Column(
        JSONB,
        nullable=False,
        default=dict,
        comment=(
            "Any additional usage metrics. "
            "E.g. {api_calls_today: 45000, active_branches: 2}"
        ),
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    subscription = relationship(
        "TenantSubscription",
        back_populates="usage_records",
        foreign_keys=[subscription_id],
    )

    def __repr__(self) -> str:
        return (
            f"<UsageSnapshot tenant_id={self.tenant_id} "
            f"date={self.snapshot_date} students={self.active_student_count}>"
        )


# ═══════════════════════════════════════════════════════════════════════════════
# TENANT FEATURE FLAG
# ═══════════════════════════════════════════════════════════════════════════════

class TenantFeatureFlag(BaseModel):
    """
    Granular per-tenant feature toggle.

    Allows enabling or disabling specific features independently of the
    subscription plan. One row per feature per tenant.

    Why per-row instead of a single JSONB column on tenants?
      - Each flag has its own enable/disable timestamp and actor
      - Flags can have individual expiry dates (temporary early access)
      - Querying "which tenants have feature X" is efficient
      - Audit trail per flag

    Examples of feature_key values:
      'AI_LESSON_SUGGESTIONS'     → GPT-powered lesson plan suggestions
      'PARENT_WHATSAPP_ALERTS'    → WhatsApp notification channel
      'ADVANCED_ANALYTICS'        → BI dashboards beyond standard reports
      'BULK_STUDENT_IMPORT_V2'    → New importer in beta
      'MULTI_BRANCH'              → Multiple campuses under one tenant
      'CUSTOM_REPORT_BUILDER'     → Drag-drop report designer
      'API_WEBHOOKS'              → Webhook delivery for events
      'SSO_GOOGLE'                → Google Workspace SSO
      'SSO_MICROSOFT'             → Microsoft/Azure SSO
      'DATA_EXPORT_CSV'           → Export data to CSV
      'WHITE_LABEL_DOMAIN'        → Custom domain mapping
      'EXAM_OMR_INTEGRATION'      → OMR sheet scanning integration
    """

    __tablename__ = "tenant_feature_flags"

    # ── References ────────────────────────────────────────────────────────────
    tenant_id = Column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK → tenants.id. The tenant this flag applies to.",
    )

    # ── Flag Identity ─────────────────────────────────────────────────────────
    feature_key = Column(
        String(100),
        nullable=False,
        index=True,
        comment=(
            "Machine-readable feature key. UPPER_SNAKE_CASE. "
            "Must match the key checked in application code. "
            "E.g. 'AI_LESSON_SUGGESTIONS'"
        ),
    )

    # ── State ─────────────────────────────────────────────────────────────────
    is_enabled = Column(
        String(5),
        nullable=False,
        default="false",
        index=True,
        comment="Whether this feature is currently enabled for this tenant",
    )

    # ── Validity ──────────────────────────────────────────────────────────────
    enabled_from = Column(
        Date,
        nullable=True,
        comment="Date this feature was enabled (null = enabled immediately on creation)",
    )
    enabled_until = Column(
        Date,
        nullable=True,
        comment=(
            "Date this feature auto-disables. "
            "NULL = no expiry (permanent). "
            "Used for time-limited early access programs."
        ),
    )

    # ── Configuration ─────────────────────────────────────────────────────────
    config = Column(
        JSONB,
        nullable=False,
        default=dict,
        comment=(
            "Feature-specific configuration. "
            "E.g. for 'PARENT_WHATSAPP_ALERTS': "
            "{provider: 'gupshup', api_key_secret_ref: 'secret/tenant/gupshup'}"
        ),
    )

    # ── Audit ─────────────────────────────────────────────────────────────────
    enabled_by_user_id = Column(
        UUID(as_uuid=True),
        nullable=True,
        comment="Internal SmartSync user_id who enabled this flag",
    )
    reason = Column(
        String(500),
        nullable=True,
        comment="Why this flag was enabled/disabled. For internal audit.",
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    tenant = relationship(
        "Tenant",
        back_populates="feature_flags",
        foreign_keys=[tenant_id],
    )

    def __repr__(self) -> str:
        return (
            f"<TenantFeatureFlag tenant_id={self.tenant_id} "
            f"feature={self.feature_key!r} enabled={self.is_enabled}>"
        )
        