"""initial auth schema

Revision ID: 01
Revises: None
Create Date: 2026-06-27 14:39:47.595084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ### create api keys table
    op.create_table('api_keys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Owning tenant. Soft FK -> platform.tenants.id'),
    sa.Column('key_name', sa.String(length=255), nullable=False, comment='Human-readable key name'),
    sa.Column('key_hash', sa.Text(), nullable=False, comment='SHA-256 hash of the actual API key'),
    sa.Column('key_prefix', sa.String(length=20), nullable=False, comment='First 8 chars for UI identification (ss_xxxx...)'),
    sa.Column('service_name', sa.String(length=100), nullable=True, comment='Calling service name (e.g. academic-service)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), nullable=False, comment='Allowed permission scopes'),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False, comment='Requests per hour limit'),
    sa.Column('allowed_ips', postgresql.ARRAY(sa.Text()), nullable=False, comment='Allowed source IPs (empty = all allowed)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Key expiry (null = never expires)'),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth',
    comment='Service-to-service and integration API keys'
    )
    op.create_index(op.f('ix_auth_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False, schema='auth')

    ### create permissions table
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False, comment="Full dotted permission code. MODULE.SUBMODULE.ACTION. Used in JWT 'permissions' claim. E.g. 'ACADEMICS.HOMEWORK.CREATE'"),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Human-readable name. E.g. 'Create Homework'"),
    sa.Column('description', sa.Text(), nullable=True, comment='What this permission allows the user to do'),
    sa.Column('module', sa.String(length=50), nullable=False, comment="Top-level module. E.g. 'ACADEMICS', 'FINANCE', 'HOSTEL'"),
    sa.Column('submodule', sa.String(length=100), nullable=False, comment="Resource within the module. E.g. 'HOMEWORK', 'FEES', 'ROOM'"),
    sa.Column('action', sa.String(length=50), nullable=False, comment="Operation being performed. E.g. 'CREATE', 'READ', 'UPDATE', 'DELETE', 'APPROVE', 'MARK', 'COLLECT', 'EXPORT', 'PUBLISH', 'ALLOCATE', 'ISSUE'"),
    sa.Column('risk_level', sa.String(length=10), nullable=False, comment='Sensitivity of this permission. LOW = read-only or routine. MEDIUM = writes or side effects. HIGH = financial, admin, or destructive operations.'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_auth_permission_code'),
    schema='auth',
    comment='Platform-defined permission catalog. Schools cannot create permissions.'
    )
    op.create_index('ix_auth_permission_module', 'permissions', ['module'], unique=False, schema='auth')
    op.create_index('ix_auth_permission_module_submodule', 'permissions', ['module', 'submodule'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_permissions_code'), 'permissions', ['code'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_permissions_is_active'), 'permissions', ['is_active'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_permissions_module'), 'permissions', ['module'], unique=False, schema='auth')

    ### create roles table
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment="Machine-readable role code. UPPER_SNAKE_CASE. Used in JWT 'role' claim and permission checks. E.g. 'CLASS_TEACHER', 'HOD', 'PRINCIPAL'"),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Human-readable display name. E.g. 'Class Teacher'"),
    sa.Column('description', sa.Text(), nullable=True, comment='Description of what this role represents. No business-domain detail.'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Broad category for grouping in UI. ACADEMIC | ADMINISTRATIVE | OPERATIONAL | SUPPORT | SYSTEM'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False = retired/deprecated role. Existing assignments are unaffected.'),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_auth_role_code'),
    schema='auth',
    comment='Platform-defined top-level role catalog. Schools cannot create roles.'
    )
    op.create_index('ix_auth_role_category', 'roles', ['category'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_roles_category'), 'roles', ['category'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_roles_code'), 'roles', ['code'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_roles_is_active'), 'roles', ['is_active'], unique=False, schema='auth')

    ### create users table
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Owning tenant. Soft FK → platform.tenants.id (no hard FK across service database boundaries).'),
    sa.Column('school_id', sa.BigInteger(), nullable=False, comment='Owning school. Soft FK → platform.schools.id.'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique login handle within (tenant_id, school_id). Set once at creation by the school admin or onboarding flow. Never changed after creation — see PATCH /users/:id/username being intentionally absent from the endpoint list below.'),
    sa.Column('email', sa.String(length=255), nullable=True, comment="Contact + recovery email. Nullable because young students may not have one — in that case a parent's email is typically used for notifications instead, tracked at the Academic Service profile level."),
    sa.Column('mobile_number', sa.String(length=10), nullable=True, comment="E.164 format, e.g. '+919876543210'. Used for SMS OTP and password delivery."),
    sa.Column('first_name', sa.String(length=50), nullable=False, comment='Given name.'),
    sa.Column('middle_name', sa.String(length=50), nullable=True, comment='Optional middle name.'),
    sa.Column('last_name', sa.String(length=50), nullable=False, comment='Family/surname.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False = account disabled by school admin (does not delete the row; use is_deleted from BaseModel for actual removal).True for every admin-created user at creation time. Forces the mandatory change-password step on first successful login before any other endpoint becomes accessible. Set to False once the user completes their first self-chosen password.'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment="Derived/cached flag: True only when at least the primary contact channel (email OR mobile, per tenant policy) is verified. The authoritative per-channel state lives on UserVerification — this column exists purely so list/filter queries on `users` don't need a join to UserVerification for the common case."),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'school_id', 'email', name='uq_users_tenant_school_email'),
    sa.UniqueConstraint('tenant_id', 'school_id', 'mobile_number', name='uq_users_tenant_school_mobile'),
    sa.UniqueConstraint('tenant_id', 'school_id', 'username', name='uq_users_tenant_school_username'),
    schema='auth',
    comment='Central identity table. One row per user per school. Holds profile/contact info only — no password, no login security state.'
    )
    op.create_index('idx_users_name', 'users', ['last_name', 'first_name'], unique=False, schema='auth')
    op.create_index('idx_users_tenant_school_active', 'users', ['tenant_id', 'school_id', 'is_active'], unique=False, schema='auth')
    op.create_index('idx_users_tenant_school', 'users', ['tenant_id', 'school_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_is_active'), 'users', ['is_active'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_is_verified'), 'users', ['is_verified'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_school_id'), 'users', ['school_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_tenant_id'), 'users', ['tenant_id'], unique=False, schema='auth')

    ### create audit logs table
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='Owning tenant. Soft FK -> platform.tenants.id'),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False, comment='CREATE | UPDATE | DELETE | LOGIN | LOGOUT | APPROVE ...'),
    sa.Column('resource_type', sa.String(length=100), nullable=False, comment='USER | ROLE | PERMISSION | TENANT ...'),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON snapshot before change'),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON snapshot after change'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='Correlation request ID'),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='SUCCESS | FAILED'),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth',
    comment='Immutable audit trail — partitioned by month'
    )
    op.create_index(op.f('ix_auth_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='auth')

    ### create auth_events table
    op.create_table('auth_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True, comment='Owning tenant. Soft FK -> platform.tenants.id'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='USER_CREATED | ROLE_ASSIGNED | ...'),
    sa.Column('event_version', sa.String(length=10), nullable=False, comment='Schema version of event_data'),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False, comment='USER | ROLE | TENANT'),
    sa.Column('aggregate_id', sa.BigInteger(), nullable=False, comment='ID of the aggregate root'),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full event payload (immutable once written)'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='User who triggered the event'),
    sa.Column('correlation_id', sa.BigInteger(), nullable=True, comment='Groups related events (e.g. one request)'),
    sa.Column('causation_id', sa.BigInteger(), nullable=True, comment='ID of the event that caused this event'),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True, comment='Exponential backoff next retry'),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth',
    comment='Event outbox for reliable async event publishing'
    )
    op.create_index(op.f('ix_auth_auth_events_aggregate_id'), 'auth_events', ['aggregate_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_auth_events_aggregate_type'), 'auth_events', ['aggregate_type'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_auth_events_correlation_id'), 'auth_events', ['correlation_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_auth_events_event_type'), 'auth_events', ['event_type'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_auth_events_is_published'), 'auth_events', ['is_published'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_auth_events_tenant_id'), 'auth_events', ['tenant_id'], unique=False, schema='auth')

    ### create ip whitelist table
    op.create_table('ip_whitelist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Owning tenant. Soft FK -> platform.tenants.id'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Single IP address (IPv4 or IPv6)'),
    sa.Column('cidr_notation', sa.String(length=50), nullable=True, comment='CIDR range e.g. 192.168.1.0/24'),
    sa.Column('ip_range_start', sa.String(length=45), nullable=True, comment='IP range start'),
    sa.Column('ip_range_end', sa.String(length=45), nullable=True, comment='IP range end'),
    sa.Column('label', sa.String(length=255), nullable=True, comment="Human-readable label e.g. 'School Campus LAN'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth',
    comment='IP whitelist for tenant access control'
    )
    op.create_index(op.f('ix_auth_ip_whitelist_ip_address'), 'ip_whitelist', ['ip_address'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_ip_whitelist_tenant_id'), 'ip_whitelist', ['tenant_id'], unique=False, schema='auth')

    ### create role permission templates table
    op.create_table('role_permission_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_auth_role_permission_template'),
    schema='auth',
    comment="Platform's default many-to-many role-permission map. Read-only for schools. Schools layer additional grants via SchoolRolePermission (permission import between roles)."
    )
    op.create_index(op.f('ix_auth_role_permission_templates_permission_id'), 'role_permission_templates', ['permission_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_role_permission_templates_role_id'), 'role_permission_templates', ['role_id'], unique=False, schema='auth')
    op.create_index('ix_auth_rpt_permission_id', 'role_permission_templates', ['permission_id'], unique=False, schema='auth')
    op.create_index('ix_auth_rpt_role_id', 'role_permission_templates', ['role_id'], unique=False, schema='auth')

    ### create school role permissions table
    op.create_table('school_role_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment="The role this permission is being imported FROM. E.g. TEACHER. Kept (rather than just storing the permission) so the whole import can be queried/revoked as 'everything imported from TEACHER into PRINCIPAL', not just permission-by-permission."),
    sa.Column('permission_id', sa.BigInteger(), nullable=False, comment='The specific permission being imported from role_id onto target_role_id.'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'school_id', 'role_id', 'permission_id', name='uq_auth_school_role_permission'),
    schema='auth',
    comment='Per-school permission import: copies a permission grant from one role (role_id) onto another role (target_role_id) for this school only. Layered on top of RolePermissionTemplate at JWT generation time, never replaces it.'
    )
    op.create_index(op.f('ix_auth_school_role_permissions_permission_id'), 'school_role_permissions', ['permission_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_school_role_permissions_role_id'), 'school_role_permissions', ['role_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_school_role_permissions_school_id'), 'school_role_permissions', ['school_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_school_role_permissions_tenant_id'), 'school_role_permissions', ['tenant_id'], unique=False, schema='auth')
    op.create_index('ix_auth_srp_lookup', 'school_role_permissions', ['school_id', 'role_id', 'permission_id'], unique=False, schema='auth')
    op.create_index('ix_auth_srp_permission', 'school_role_permissions', ['permission_id'], unique=False, schema='auth')
    op.create_index('ix_auth_srp_source_role', 'school_role_permissions', ['role_id'], unique=False, schema='auth')
    op.create_index('ix_auth_srp_tenant_school', 'school_role_permissions', ['tenant_id', 'school_id'], unique=False, schema='auth')

    ### create school role stats table
    op.create_table('school_role_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Org boundary. Soft FK -> platform.tenants.id'),
    sa.Column('school_id', sa.BigInteger(), nullable=False, comment='School boundary. Soft FK -> platform.schools.id'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='Platform role ID. FK -> auth.roles.id'),
    sa.Column('total_users', sa.SmallInteger(), nullable=False, comment='Total users assigned to this role (including inactive/deleted). Counts all user_roles records regardless of user.is_active or user.is_deleted.'),
    sa.Column('active_users', sa.SmallInteger(), nullable=False, comment='Active users with this role. WHERE user.is_active = true AND user.is_deleted = false AND user_role.is_active = true.'),
    sa.Column('inactive_users', sa.SmallInteger(), nullable=False, comment='Inactive users with this role. WHERE user.is_active = false AND user.is_deleted = false.'),
    sa.Column('deleted_users', sa.SmallInteger(), nullable=False, comment='Soft deleted users who had this role. WHERE user.is_deleted = true.'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'school_id', 'role_id', name='uq_auth_school_role_stats'),
    schema='auth',
    comment='Real-time user count per role per school. Automatically updated by triggers on user_roles and users tables. Single source of truth for role-based subscription usage.'
    )
    op.create_index(op.f('ix_auth_school_role_stats_role_id'), 'school_role_stats', ['role_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_school_role_stats_school_id'), 'school_role_stats', ['school_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_school_role_stats_tenant_id'), 'school_role_stats', ['tenant_id'], unique=False, schema='auth')
    op.create_index('ix_auth_srs_role', 'school_role_stats', ['role_id'], unique=False, schema='auth')
    op.create_index('ix_auth_srs_school', 'school_role_stats', ['school_id'], unique=False, schema='auth')
    op.create_index('ix_auth_srs_school_role', 'school_role_stats', ['school_id', 'role_id'], unique=False, schema='auth')
    op.create_index('ix_auth_srs_tenant_school', 'school_role_stats', ['tenant_id', 'school_id'], unique=False, schema='auth')

    ### create user credentials table
    op.create_table('user_credentials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='FK → users.id. Unique enforces strict 1-to-1.'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Argon2id hash of the current password. The school-admin-generated random alphanumeric temporary password is hashed into this field immediately on user creation — never stored in plaintext anywhere.'),
    sa.Column('password_expired_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp after which the password must be changed (tenant-level password-age policy, if enabled). NULL = no expiry enforced.'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True, comment='When the password was last changed by the user themselves.'),
    sa.Column('password_change_count', sa.SmallInteger(), nullable=False, comment='Lifetime count of password changes. Useful for security analytics.'),
    sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.text('false'), comment='True for every admin-created user at creation time (temp password issued). Forces the change-password flow on first login before any other endpoint becomes accessible. Set to False once the user completes their first self-chosen password.'),
    sa.Column('max_concurrent_sessions', sa.SmallInteger(), nullable=True, comment='Per-user override for max concurrent sessions. NULL = use tenant default. Checked at login time before creating a new session row. If user already has N active sessions and this limit is reached, oldest session is revoked (or login is blocked based on tenant policy).'),
    sa.Column('is_locked', sa.Boolean(), nullable=False, comment='True after failed_login_attempt crosses the configured threshold. Blocks login entirely until unlocked by admin or lockout window elapses (see locked_until).'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Auto-unlock timestamp for time-based lockouts (e.g. 15-minute lockout after 5 failed attempts). NULL with is_locked=True means a permanent lock requiring manual admin unlock.'),
    sa.Column('failed_login_attempt', sa.SmallInteger(), nullable=False, comment='Consecutive failed attempts since the last successful login. Resets to 0 on success.'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent successful login.'),
    sa.Column('last_login_ip', postgresql.INET(), nullable=True, comment='IP address of the most recent successful login.'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth',
    comment='1-to-1 with users. Password hash and all login-security counters. Isolated so login writes never lock profile reads.'
    )
    op.create_index(op.f('ix_auth_user_credentials_is_locked'), 'user_credentials', ['is_locked'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_credentials_user_id'), 'user_credentials', ['user_id'], unique=True, schema='auth')

    ### create user otps table
    op.create_table('user_otps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Owning tenant. Soft FK → platform.tenants.id. Denormalized here for efficient multi-tenant queries and data isolation.'),
    sa.Column('school_id', sa.BigInteger(), nullable=False, comment='Owning school. Soft FK → platform.schools.id. Denormalized for admin dashboards and school-level OTP analytics.'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='FK → users.id. CASCADE deletes OTP rows when the user is deleted.'),
    sa.Column('otp_type', sa.Enum('EMAIL_VERIFY', 'MOBILE_VERIFY', 'PASSWORD_RESET', name='otp_type_enum', schema='auth'), nullable=False, comment='Purpose of this OTP. EMAIL_VERIFY    → Email verification during signup or email change. MOBILE_VERIFY   → Mobile number verification during signup or phone change. PASSWORD_RESET  → Password reset flow (forgot password).'),
    sa.Column('target_channel', sa.Enum('EMAIL', 'SMS', name='otp_channel_enum', schema='auth'), nullable=False, comment='Delivery channel for this OTP. EMAIL → Sent via email service. SMS   → Sent via SMS gateway (Twilio, AWS SNS, etc.).'),
    sa.Column('target_address', sa.String(length=255), nullable=False, comment='The email address or mobile number the OTP was sent to. Kept for audit even if the user later changes their email/mobile. Format: email@example.com for EMAIL, +919876543210 for SMS.'),
    sa.Column('code_hash', sa.String(length=255), nullable=False, comment='SHA-256 hash of the OTP code. The raw 6-digit code is returned once to the delivery channel (email/SMS) and is never stored in plaintext.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='OTP is invalid after this time. Default: 5 minutes from creation.'),
    sa.Column('attempts_used', sa.Integer(), nullable=False, comment='Number of wrong OTP attempts submitted by the user. Resets to 0 on success.'),
    sa.Column('max_attempts', sa.Integer(), nullable=False, comment='Maximum allowed attempts before the OTP is blocked. Configurable per tenant.'),
    sa.Column('is_blocked', sa.Boolean(), nullable=False, comment='True after attempts_used >= max_attempts. Blocks further validation attempts.'),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True, comment='Cooldown timestamp after which the user can request a new OTP. NULL if not blocked. Default cooldown: 15 minutes.'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='True once the OTP has been successfully validated and consumed.'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='When the OTP was successfully consumed.'),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='IP address of the client that requested the OTP.'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User-Agent from the OTP request.'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth',
    comment='Generic OTP store. Redis is primary; this is the durable fallback and attempt-tracking source of truth.'
    )
    op.create_index('ix_auth_otp_expires', 'user_otps', ['expires_at'], unique=False, schema='auth')
    op.create_index('ix_auth_otp_target', 'user_otps', ['target_address', 'created_at'], unique=False, schema='auth')
    op.create_index('ix_auth_otp_tenant_school', 'user_otps', ['tenant_id', 'school_id', 'created_at'], unique=False, schema='auth')
    op.create_index('ix_auth_otp_user_type', 'user_otps', ['user_id', 'otp_type', 'is_used'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_otps_code_hash'), 'user_otps', ['code_hash'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_otps_expires_at'), 'user_otps', ['expires_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_otps_is_used'), 'user_otps', ['is_used'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_otps_school_id'), 'user_otps', ['school_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_otps_tenant_id'), 'user_otps', ['tenant_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_otps_user_id'), 'user_otps', ['user_id'], unique=False, schema='auth')

    ### create user roles  table
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='FK -> users.id. Unique: enforces one role row per user, period.'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='The single platform role this user holds. RESTRICT prevents accidental role deletion.'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'school_id', 'user_id', name='uq_auth_user_role_single'),
    schema='auth',
    comment='Exactly one role per user per school. Unique constraint has no role_id — a user cannot hold a second role row.'
    )
    op.create_index('ix_auth_user_role_role', 'user_roles', ['role_id', 'school_id'], unique=False, schema='auth')
    op.create_index('ix_auth_user_role_user', 'user_roles', ['user_id', 'school_id', 'role_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_roles_role_id'), 'user_roles', ['role_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_roles_school_id'), 'user_roles', ['school_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_roles_tenant_id'), 'user_roles', ['tenant_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_roles_user_id'), 'user_roles', ['user_id'], unique=True, schema='auth')
    op.create_index('ix_auth_user_role_tenant_school', 'user_roles', ['tenant_id', 'school_id'], unique=False, schema='auth')

    ### create user sessions table
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Owning tenant. Soft FK → platform.tenants.id. Denormalized here (not joined through users) so that admin dashboards can list all active sessions in a tenant without a cross-table join. Required for efficient data isolation queries.'),
    sa.Column('school_id', sa.BigInteger(), nullable=False, comment="Owning school. Soft FK → platform.schools.id. Denormalized for school-level session analytics and admin dashboards (e.g., 'active sessions in this school' without joining to users table)."),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='FK → users.id. CASCADE deletes all sessions when the user is deleted.'),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False, comment='SHA-256 hash of the opaque refresh token. The raw refresh token is returned once to the client on login and is never stored in plaintext. Used by the /auth/refresh endpoint to issue a new access token and rotate the refresh token.'),
    sa.Column('device_id', sa.String(length=255), nullable=True, comment="Client-generated device fingerprint. Optional — used for 'log out all devices' and limiting concurrent sessions."),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment="Raw User-Agent header from the login request. Shown in 'active sessions' list."),
    sa.Column('ip_address', postgresql.INET(), nullable=True, comment='Client IP at login time. From request.remote_addr or X-Forwarded-For.'),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True, comment='Updated on each authenticated API request. Used for idle timeout.'),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False, comment='Refresh token expiry. Default: 30 days from login.'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth',
    comment='Active user sessions. One row per login per device. Refresh tokens live here, not in the users table.'
    )
    op.create_index('ix_auth_session_refresh_expires', 'user_sessions', ['refresh_expires_at'], unique=False, schema='auth')
    op.create_index('ix_auth_session_school_active', 'user_sessions', ['school_id', 'refresh_expires_at'], unique=False, schema='auth')
    op.create_index('ix_auth_session_user_active', 'user_sessions', ['user_id', 'refresh_expires_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_sessions_device_id'), 'user_sessions', ['device_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_sessions_refresh_expires_at'), 'user_sessions', ['refresh_expires_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_user_sessions_school_id'), 'user_sessions', ['school_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_sessions_tenant_id'), 'user_sessions', ['tenant_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_auth_session_tenant_school', 'user_sessions', ['tenant_id', 'school_id'], unique=False, schema='auth')

    ### create user verifications table
    op.create_table('user_verifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='FK → users.id. Unique enforces strict 1-to-1.'),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='True once the user has confirmed access to the email on their User row.'),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True, comment='When email verification completed.'),
    sa.Column('mobile_number_verified', sa.Boolean(), nullable=False, comment='True once the user has confirmed access to the mobile number via OTP.'),
    sa.Column('mobile_number_verified_at', sa.DateTime(timezone=True), nullable=True, comment='When mobile verification completed.'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth',
    comment='1-to-1 with users. Per-channel verification outcome only — OTP codes themselves live in Redis, not here.'
    )
    op.create_index(op.f('ix_auth_user_verifications_user_id'), 'user_verifications', ['user_id'], unique=True, schema='auth')

    ### create user tokens table
    op.create_table('user_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False, comment='JWT ID. Used for single-use enforcement and revocation.'),
    sa.Column('purpose', sa.String(length=20), nullable=False, comment='ONBOARDING | PASSWORD_RESET'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token hard expiry. 48hr for onboarding, 1hr for password reset.'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='When token was consumed. NULL = not yet used.'),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    schema='auth',
    comment='Single-use tokens for onboarding and password reset links.'
    )
    op.create_index('idx_user_token_jti', 'user_tokens', ['jti'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_tokens_user_id'), table_name='user_tokens', schema='auth')
    op.drop_index('idx_user_token_jti', table_name='user_tokens', schema='auth')
    op.drop_table('user_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_user_verifications_user_id'), table_name='user_verifications', schema='auth')
    op.drop_table('user_verifications', schema='auth')
    op.drop_index(op.f('ix_auth_user_sessions_user_id'), table_name='user_sessions', schema='auth')
    op.drop_index(op.f('ix_auth_user_sessions_tenant_id'), table_name='user_sessions', schema='auth')
    op.drop_index(op.f('ix_auth_user_sessions_school_id'), table_name='user_sessions', schema='auth')
    op.drop_index(op.f('ix_auth_user_sessions_refresh_token_hash'), table_name='user_sessions', schema='auth')
    op.drop_index(op.f('ix_auth_user_sessions_refresh_expires_at'), table_name='user_sessions', schema='auth')
    op.drop_index(op.f('ix_auth_user_sessions_device_id'), table_name='user_sessions', schema='auth')
    op.drop_index('ix_auth_session_user_active', table_name='user_sessions', schema='auth')
    op.drop_index('ix_auth_session_school_active', table_name='user_sessions', schema='auth')
    op.drop_index('ix_auth_session_refresh_expires', table_name='user_sessions', schema='auth')
    op.drop_table('user_sessions', schema='auth')
    op.drop_index(op.f('ix_auth_user_roles_user_id'), table_name='user_roles', schema='auth')
    op.drop_index(op.f('ix_auth_user_roles_tenant_id'), table_name='user_roles', schema='auth')
    op.drop_index(op.f('ix_auth_user_roles_school_id'), table_name='user_roles', schema='auth')
    op.drop_index(op.f('ix_auth_user_roles_role_id'), table_name='user_roles', schema='auth')
    op.drop_index('ix_auth_user_role_user', table_name='user_roles', schema='auth')
    op.drop_index('ix_auth_user_role_role', table_name='user_roles', schema='auth')
    op.drop_table('user_roles', schema='auth')
    op.drop_index(op.f('ix_auth_user_otps_user_id'), table_name='user_otps', schema='auth')
    op.drop_index(op.f('ix_auth_user_otps_tenant_id'), table_name='user_otps', schema='auth')
    op.drop_index(op.f('ix_auth_user_otps_school_id'), table_name='user_otps', schema='auth')
    op.drop_index(op.f('ix_auth_user_otps_is_used'), table_name='user_otps', schema='auth')
    op.drop_index(op.f('ix_auth_user_otps_expires_at'), table_name='user_otps', schema='auth')
    op.drop_index(op.f('ix_auth_user_otps_code_hash'), table_name='user_otps', schema='auth')
    op.drop_index('ix_auth_otp_user_type', table_name='user_otps', schema='auth')
    op.drop_index('ix_auth_otp_tenant_school', table_name='user_otps', schema='auth')
    op.drop_index('ix_auth_otp_target', table_name='user_otps', schema='auth')
    op.drop_index('ix_auth_otp_expires', table_name='user_otps', schema='auth')
    op.drop_table('user_otps', schema='auth')
    op.drop_index(op.f('ix_auth_user_credentials_user_id'), table_name='user_credentials', schema='auth')
    op.drop_index(op.f('ix_auth_user_credentials_is_locked'), table_name='user_credentials', schema='auth')
    op.drop_table('user_credentials', schema='auth')
    op.drop_index('ix_auth_srs_school_role', table_name='school_role_stats', schema='auth')
    op.drop_index('ix_auth_srs_school', table_name='school_role_stats', schema='auth')
    op.drop_index('ix_auth_srs_role', table_name='school_role_stats', schema='auth')
    op.drop_index(op.f('ix_auth_school_role_stats_tenant_id'), table_name='school_role_stats', schema='auth')
    op.drop_index(op.f('ix_auth_school_role_stats_school_id'), table_name='school_role_stats', schema='auth')
    op.drop_index(op.f('ix_auth_school_role_stats_role_id'), table_name='school_role_stats', schema='auth')
    op.drop_table('school_role_stats', schema='auth')
    op.drop_index('ix_auth_srp_source_role', table_name='school_role_permissions', schema='auth')
    op.drop_index('ix_auth_srp_permission', table_name='school_role_permissions', schema='auth')
    op.drop_index('ix_auth_srp_lookup', table_name='school_role_permissions', schema='auth')
    op.drop_index(op.f('ix_auth_school_role_permissions_tenant_id'), table_name='school_role_permissions', schema='auth')
    op.drop_index(op.f('ix_auth_school_role_permissions_school_id'), table_name='school_role_permissions', schema='auth')
    op.drop_index(op.f('ix_auth_school_role_permissions_role_id'), table_name='school_role_permissions', schema='auth')
    op.drop_index(op.f('ix_auth_school_role_permissions_permission_id'), table_name='school_role_permissions', schema='auth')
    op.drop_table('school_role_permissions', schema='auth')
    op.drop_index('ix_auth_rpt_role_id', table_name='role_permission_templates', schema='auth')
    op.drop_index('ix_auth_rpt_permission_id', table_name='role_permission_templates', schema='auth')
    op.drop_index(op.f('ix_auth_role_permission_templates_role_id'), table_name='role_permission_templates', schema='auth')
    op.drop_index(op.f('ix_auth_role_permission_templates_permission_id'), table_name='role_permission_templates', schema='auth')
    op.drop_table('role_permission_templates', schema='auth')
    op.drop_index(op.f('ix_auth_ip_whitelist_tenant_id'), table_name='ip_whitelist', schema='auth')
    op.drop_index(op.f('ix_auth_ip_whitelist_ip_address'), table_name='ip_whitelist', schema='auth')
    op.drop_table('ip_whitelist', schema='auth')
    op.drop_index(op.f('ix_auth_auth_events_tenant_id'), table_name='auth_events', schema='auth')
    op.drop_index(op.f('ix_auth_auth_events_is_published'), table_name='auth_events', schema='auth')
    op.drop_index(op.f('ix_auth_auth_events_event_type'), table_name='auth_events', schema='auth')
    op.drop_index(op.f('ix_auth_auth_events_correlation_id'), table_name='auth_events', schema='auth')
    op.drop_index(op.f('ix_auth_auth_events_aggregate_type'), table_name='auth_events', schema='auth')
    op.drop_index(op.f('ix_auth_auth_events_aggregate_id'), table_name='auth_events', schema='auth')
    op.drop_table('auth_events', schema='auth')
    op.drop_index(op.f('ix_auth_audit_logs_user_id'), table_name='audit_logs', schema='auth')
    op.drop_index(op.f('ix_auth_audit_logs_tenant_id'), table_name='audit_logs', schema='auth')
    op.drop_index(op.f('ix_auth_audit_logs_resource_type'), table_name='audit_logs', schema='auth')
    op.drop_index(op.f('ix_auth_audit_logs_resource_id'), table_name='audit_logs', schema='auth')
    op.drop_index(op.f('ix_auth_audit_logs_request_id'), table_name='audit_logs', schema='auth')
    op.drop_index(op.f('ix_auth_audit_logs_action'), table_name='audit_logs', schema='auth')
    op.drop_table('audit_logs', schema='auth')
    op.drop_index(op.f('ix_auth_users_tenant_id'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_school_id'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_is_verified'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_is_active'), table_name='users', schema='auth')
    op.drop_index('idx_users_tenant_school_active', table_name='users', schema='auth')
    op.drop_index('idx_users_name', table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_roles_is_active'), table_name='roles', schema='auth')
    op.drop_index(op.f('ix_auth_roles_code'), table_name='roles', schema='auth')
    op.drop_index(op.f('ix_auth_roles_category'), table_name='roles', schema='auth')
    op.drop_index('ix_auth_role_category', table_name='roles', schema='auth')
    op.drop_table('roles', schema='auth')
    op.drop_index(op.f('ix_auth_permissions_module'), table_name='permissions', schema='auth')
    op.drop_index(op.f('ix_auth_permissions_is_active'), table_name='permissions', schema='auth')
    op.drop_index(op.f('ix_auth_permissions_code'), table_name='permissions', schema='auth')
    op.drop_index('ix_auth_permission_module_submodule', table_name='permissions', schema='auth')
    op.drop_index('ix_auth_permission_module', table_name='permissions', schema='auth')
    op.drop_table('permissions', schema='auth')
    op.drop_index(op.f('ix_auth_api_keys_tenant_id'), table_name='api_keys', schema='auth')
    op.drop_index(op.f('ix_auth_api_keys_key_hash'), table_name='api_keys', schema='auth')
    op.drop_table('api_keys', schema='auth')
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS auth.otp_type_enum")
    op.execute("DROP TYPE IF EXISTS auth.otp_channel_enum")
    # ### end Alembic commands ###
