"""initial_platform_schema

Revision ID: 01
Revises: None
Create Date: 2026-06-27 12:34:35.898034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    ### create expansion addons table
    op.create_table('expansion_addons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Unique addon code for multi-tenant support'),
    sa.Column('expansion_type', sa.Enum('USER_CAPACITY_EXPANSION', name='expansion_type', schema='platform'), nullable=False),
    sa.Column('user_count', sa.Enum('PLUS_500', 'PLUS_1000', name='expansion_user_count', schema='platform'), nullable=False),
    sa.Column('tenure', sa.Enum('ONE_MONTH', 'THREE_MONTHS', 'SIX_MONTHS', 'TWELVE_MONTHS', 'TWENTY_FOUR', 'THIRTY_SIX', name='addon_tenure', schema='platform'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('storage', sa.Enum('GB_20', 'GB_30', 'GB_50', 'GB_100', 'GB_150', 'GB_200', 'GB_250', 'GB_300', 'GB_350', 'GB_400', 'GB_450', 'GB_500', name='storage_limit', schema='platform'), nullable=False, comment='Storage package label in GB; enum value is in MB'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('price > 0', name='positive_addon_price'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('uq_addons_code_active', 'expansion_addons', ['code'], unique=True, schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    
    ### create plans table
    op.create_table('plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Unique plan code for multi-tenant support'),
    sa.Column('type', sa.Enum('CORE', 'GROWTH', 'TRIAL', name='plan_type', schema='platform'), nullable=False),
    sa.Column('variant', sa.Enum('ENTRY', 'SCALABLE', name='plan_variant', schema='platform'), nullable=False),
    sa.Column('user_count', sa.Enum('USERS_500', 'USERS_1000', 'USERS_1500', 'USERS_2500', 'USERS_3500', 'USERS_4500', 'USERS_5500', 'USERS_2000', 'USERS_3000', 'USERS_4000', 'USERS_5000', name='plan_user_count', schema='platform'), nullable=False, comment='Allowed user count for the plan'),
    sa.Column('tenure', sa.Enum('ONE_MONTH', 'THREE_MONTHS', 'SIX_MONTHS', 'TWELVE_MONTHS', 'TWENTY_FOUR', 'THIRTY_SIX', name='plan_tenure', schema='platform'), nullable=False, comment='Tenure duration in months'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Pricing or MRP per user per month'),
    sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Discounted price per user per month'),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True, comment='Discount percentage'),
    sa.Column('storage', sa.Enum('GB_20', 'GB_30', 'GB_50', 'GB_100', 'GB_150', 'GB_200', 'GB_250', 'GB_300', 'GB_350', 'GB_400', 'GB_450', 'GB_500', name='storage_limit', schema='platform'), nullable=False, comment='Storage package label in GB; enum value is in MB'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('price > 0', name='positive_price'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('ix_plans_type_variant_active', 'plans', ['type', 'variant'], unique=False, schema='platform', postgresql_where=sa.text('is_active = TRUE AND deleted_at IS NULL'))
    op.create_index('uq_plans_code_active', 'plans', ['code'], unique=True, schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    
    ### create tenants table
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Unique tenant code for multi-tenant support'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='tenant_status', schema='platform'), server_default='ACTIVE', nullable=False),
    sa.Column('type', sa.Enum('SINGLE_SCHOOL', 'SCHOOL_GROUP', 'GOVERNMENT_BLOCK', 'UNIVERSITY', name='tenant_type_enum', schema='platform'), server_default='SINGLE_SCHOOL', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('uq_tenants_code_active', 'tenants', ['code'], unique=True, schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_tenants_slug_active', 'tenants', ['slug'], unique=True, schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    
    ### create schools tables
    op.create_table('schools',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Unique school code for multi-tenant support'),
    sa.Column('board', sa.Enum('CBSE', 'ICSE', 'STATE', 'IB', 'IGCSE', name='board_type', schema='platform'), server_default='CBSE', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', 'ARCHIVED', name='school_status', schema='platform'), server_default='PENDING', nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True, comment="Indian state name or code, e.g. 'Karnataka' or 'KA'"),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True, comment='Indian PIN code. String to preserve leading zeros.'),
    sa.Column('address', sa.Text(), nullable=True, comment='Full street address / landmark line'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['platform.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('ix_schools_state_city', 'schools', ['state', 'city'], unique=False, schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_schools_tenant_id_active', 'schools', ['tenant_id'], unique=False, schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_schools_code_active', 'schools', ['code'], unique=True, schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_schools_subdomain_active', 'schools', ['subdomain'], unique=True, schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    
    ### create school subscription table
    op.create_table('school_subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='Denormalized from school.tenant_id for tenant-scoped queries and future sharding'),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('addon_id', sa.BigInteger(), nullable=True, comment='Addon plan ID - null by default'),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'NO_PLAN', name='subscription_status', schema='platform'), server_default='ACTIVE', nullable=False),
    sa.Column('remaining_users', sa.Integer(), nullable=False, comment='effective_max_users - current_assigned_user_count'),
    sa.Column('remaining_storage', sa.Integer(), nullable=False, comment='Remaining storage in MB'),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('remaining_users >= 0', name='remaining_non_negative'),
    sa.CheckConstraint('remaining_storage >= 0', name='remaining_storage_non_negative'),
    sa.ForeignKeyConstraint(['addon_id'], ['platform.expansion_addons.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['platform.plans.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['platform.schools.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['platform.tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('ix_subscriptions_plan_id', 'school_subscriptions', ['plan_id'], unique=False, schema='platform')
    op.create_index('ix_subscriptions_tenant_id_active', 'school_subscriptions', ['tenant_id'], unique=False, schema='platform')
    op.create_index('uq_subscriptions_school_id_active', 'school_subscriptions', ['school_id'], unique=False, schema='platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_subscriptions_school_id_active', table_name='school_subscriptions', schema='platform')
    op.drop_index('ix_subscriptions_tenant_id_active', table_name='school_subscriptions', schema='platform')
    op.drop_index('ix_subscriptions_plan_id', table_name='school_subscriptions', schema='platform')
    op.drop_table('school_subscriptions', schema='platform')
    op.drop_index('uq_schools_subdomain_active', table_name='schools', schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_schools_code_active', table_name='schools', schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_schools_tenant_id_active', table_name='schools', schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_schools_state_city', table_name='schools', schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('schools', schema='platform')
    op.drop_index('uq_tenants_slug_active', table_name='tenants', schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_tenants_code_active', table_name='tenants', schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('tenants', schema='platform')
    op.drop_index('uq_plans_code_active', table_name='plans', schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_plans_type_variant_active', table_name='plans', schema='platform', postgresql_where=sa.text('is_active = TRUE AND deleted_at IS NULL'))
    op.drop_table('plans', schema='platform')
    op.drop_index('uq_addons_code_active', table_name='expansion_addons', schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('expansion_addons', schema='platform')
    # ### end Alembic commands ###
