"""email_templates_and_sends

Revision ID: 03
Revises: 02
Create Date: 2026-07-18 17:01:17.049665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03'
down_revision: Union[str, None] = '02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Admin-facing template name, unique among non-deleted templates'),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False, comment='Rich-text-editor HTML, rendered as-is (marked `| safe`) into admin_broadcast'),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM NOW())::BIGINT'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM NOW())::BIGINT'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('uq_email_templates_name_active', 'email_templates', ['name'], unique=True, schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('email_sends',
    sa.Column('template_id', sa.BigInteger(), nullable=True, comment='Template this send was composed from, if any — ad-hoc sends leave this null'),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False, comment='Snapshot at send time — independent of any later edit to the source template'),
    sa.Column('sent_by', sa.BigInteger(), nullable=False, comment='Soft FK -> auth.users.id, no hard FK across service database boundaries'),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM NOW())::BIGINT'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM NOW())::BIGINT'), nullable=False),
    sa.CheckConstraint('recipient_count > 0', name='positive_recipient_count'),
    sa.ForeignKeyConstraint(['template_id'], ['platform.email_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('ix_email_sends_created_at', 'email_sends', ['created_at'], unique=False, schema='platform')
    op.create_index('ix_email_sends_sent_by', 'email_sends', ['sent_by'], unique=False, schema='platform')
    op.create_table('email_send_recipients',
    sa.Column('email_send_id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('notification_event_id', sa.String(length=128), nullable=True, comment='Null means the notification-api publish call itself failed to queue'),
    sa.Column('status', sa.Enum('QUEUED', 'SUCCESS', 'FAILURE', 'SKIPPED', 'UNKNOWN', name='email_recipient_status', schema='platform'), server_default='QUEUED', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM NOW())::BIGINT'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), server_default=sa.text('EXTRACT(EPOCH FROM NOW())::BIGINT'), nullable=False),
    sa.ForeignKeyConstraint(['email_send_id'], ['platform.email_sends.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='platform'
    )
    op.create_index('ix_email_send_recipients_email_send_id', 'email_send_recipients', ['email_send_id'], unique=False, schema='platform')
    op.create_index('ix_email_send_recipients_event_id', 'email_send_recipients', ['notification_event_id'], unique=False, schema='platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_send_recipients_event_id', table_name='email_send_recipients', schema='platform')
    op.drop_index('ix_email_send_recipients_email_send_id', table_name='email_send_recipients', schema='platform')
    op.drop_table('email_send_recipients', schema='platform')
    op.drop_index('ix_email_sends_sent_by', table_name='email_sends', schema='platform')
    op.drop_index('ix_email_sends_created_at', table_name='email_sends', schema='platform')
    op.drop_table('email_sends', schema='platform')
    op.drop_index('uq_email_templates_name_active', table_name='email_templates', schema='platform', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('email_templates', schema='platform')
    # ### end Alembic commands ###
    # Not auto-emitted by autogenerate (matches this repo's pre-existing pattern
    # of leaving enum types behind on downgrade for plan_type/plan_variant/etc in
    # 01_initial_platform_schema.py) — added explicitly here since it was cheap
    # to fix and otherwise breaks a downgrade-then-upgrade-again cycle outright
    # (CREATE TYPE fails with DuplicateObjectError, confirmed while testing this
    # migration against a disposable local DB).
    op.execute("DROP TYPE IF EXISTS platform.email_recipient_status")
